### ISSUE TITLE
The Transitioning name may result in a collision

### ISSUE THREAD

**Issue by ianegordon** [material-motion/motion-transitioning-objc#10]
Consider MaterialTransitioning.

**Comment by appsforartists** [comment]
Ian - are you afraid an author will be using the name "Transition" in their code and will thus have a hard time trying this library, or that there will be another project vending a library called "Transitioning"?

**Comment by jverkoey** [comment]
Ah yes - to clarify this name is only referred to in the import statements for the library. E.g.

```swift
import Transitioning
```

```objc
#import <Transitioning/Transitioning.h>
```

In all other places the API names in Objective-C have an MDM prefix and are prefix-less in Swift. If there is a conflict in Swift, the compiler will make you write `Transitioning.<API>`.

**Comment by jverkoey** [comment]
Closing - please reopen if necessary.
